# Generated by Django 5.2.4 on 2025-07-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operacao',
        ),
    ]
