# Generated by Django 5.2.4 on 2025-07-24 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0002_delete_operacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('IDOperacao', models.AutoField(primary_key=True, serialize=False)),
                ('Parametros', models.CharField(max_length=255)),
                ('Resultado', models.CharField(max_length=255)),
                ('DtInclusao', models.DateField(auto_now=True)),
                ('Usuario', models.ForeignKey(db_column='IDUsuario', on_delete=django.db.models.deletion.CASCADE, to='calculator.usuario')),
            ],
        ),
    ]
