# Generated by Django 5.2.4 on 2025-07-24 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IDUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Senha', models.CharField(max_length=255)),
                ('DtInclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('IDOperacao', models.AutoField(primary_key=True, serialize=False)),
                ('Parametros', models.CharField(max_length=255)),
                ('Resultado', models.CharField(max_length=255)),
                ('DtInclusao', models.DateField(auto_now=True)),
                ('Usuario', models.ForeignKey(db_column='IDUsuario', on_delete=django.db.models.deletion.CASCADE, to='calculator.usuario')),
            ],
        ),
    ]
